import type { AlumniProfile, FeedPost, GalleryItem } from '@/types';

export const alumniProfiles: AlumniProfile[] = [
  {
    id: '1',
    name: 'Niran Chaiyaporn',
    generation: 'Gen 18',
    department: 'Computer Science',
    faculty: 'Engineering',
    occupation: 'Principal Engineer',
    employmentType: 'Private Company',
    company: 'TechNova',
    province: 'Bangkok',
    achievement: 'Open Source Leadership Award',
    bio: 'Building reliable products for education and public services.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Suda Preecha',
    generation: 'Gen 20',
    department: 'Business Administration',
    faculty: 'Business',
    occupation: 'Founder',
    employmentType: 'Business Owner',
    company: 'Northstar Labs',
    province: 'Chiang Mai',
    achievement: 'Women in Tech Founder Award',
    bio: 'Creating venture-backed solutions for community impact.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Kritsada Phan',
    generation: 'Gen 16',
    department: 'Mechanical Engineering',
    faculty: 'Engineering',
    occupation: 'Professor',
    employmentType: 'Academic',
    company: 'KMUTT University',
    province: 'Khon Kaen',
    achievement: 'Research Excellence Award',
    bio: 'Advancing sustainable innovation and mentorship programs.',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    isFeatured: false,
  },
];

export const feedPosts: FeedPost[] = [
  {
    id: 'p1',
    author: 'Dr. Ploy',
    role: 'Alumni Relations',
    title: 'Annual reunion dinner is now open for registration',
    body: 'Join thousands of alumni for a networking evening, keynote talks, and community awards.',
    category: 'Announcement',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=900&q=80',
    likes: 142,
    comments: 31,
    createdAt: '2h ago',
    pinned: true,
  },
  {
    id: 'p2',
    author: 'Mina T.',
    role: 'Student Ambassador',
    title: 'New scholarship opportunities for Gen 22',
    body: 'A fresh round of mentorship and funding support is available for rising graduates.',
    category: 'News',
    likes: 86,
    comments: 18,
    createdAt: '5h ago',
  },
  {
    id: 'p3',
    author: 'Aran S.',
    role: 'Volunteer',
    title: 'Community service day at the old campus',
    body: 'Volunteers are gathering for the outreach event this weekend.',
    category: 'Activity',
    likes: 64,
    comments: 12,
    createdAt: 'Yesterday',
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: 'g1',
    title: 'Campus Night Walk',
    generation: 'Gen 18',
    year: '2018',
    album: 'Campus Life',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=900&q=80',
    tags: ['campus', 'night', 'networking'],
  },
  {
    id: 'g2',
    title: 'Innovation Summit',
    generation: 'Gen 20',
    year: '2020',
    album: 'Innovation',
    image: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=900&q=80',
    tags: ['leaders', 'tech'],
  },
  {
    id: 'g3',
    title: 'Spring Festival',
    generation: 'Gen 16',
    year: '2016',
    album: 'Traditions',
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=900&q=80',
    tags: ['festival', 'community'],
  },
];
